# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

remote_theme: "jeffreytse/jekyll-theme-yat"

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bradley Turner's Portfolio
email: bgt98@hotmail.com
author: Braldey Turner
description: >- # this means to ignore newlines until "baseurl:"
  A 26 year old Designer who wants a challenge!

copyright: "Copyright (cleft) 2023-{currentYear} {author}"
yat:
  date_format: "%Y-%m-%d"
sitemap: true

header_pages:
  - index.html
  - about.html
  - archives.html
  - categories.html
  - tags.html

defaults:
  home:
    heading: "Bradley Turner"
    subheading: "My Design Portfolio"
    banner: "/assets/images/banners/home.jpeg"

brand_color: "#6a93fc"

baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "https://algebuckina.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: algebuckina
github_username:  algebuckina
favicon: "favicon.ico" # the favicon for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/